from .domain_error import DomainError


class DataFrameValidationError(DomainError):
    """DataFrameの検証エラーを表すカスタム例外"""
    pass
